### ISSUE TITLE
Selecting single item in the collection rather than the whole object

### ISSUE THREAD

**Issue by xuan** [npgall/cqengine#122]
Is there a way to only select a single item in a collection rather than a __"*"__ ?   I'm trying to return only the success rather than the whole accessLogs.
```sql
SELECT success FROM accessLogs WHERE success = true ORDER BY timestamp DESC
```

Example:
```java
public class AccessLog {
        boolean success;
        Timestamp timestamp;
        ....
}
....
SQLParser parser = SQLParser.forPojoWithAttributes(AccessLog.class, createAttributes(AccessLog.class));
        IndexedCollection<String> accessLogs = new ConcurrentIndexedCollection<>();
        ResultSet<String> results = parser.retrieve(accessLogs, "SELECT success FROM accessLogs WHERE success = true ORDER BY timestamp DESC");
        for (String accessLog : results) 
            logger.debug("accessLog: " + accessLog);
```

Right now, I'm getting this exception:
```
com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:7: mismatched input 'accessLogs' expecting '*'

	at com.googlecode.cqengine.query.parser.common.QueryParser$1.syntaxError(QueryParser.java:54)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:558)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:150)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.start(SQLGrammarParser.java:263)
	at com.googlecode.cqengine.query.parser.sql.SQLParser.parse(SQLParser.java:62)
	at com.googlecode.cqengine.query.parser.common.QueryParser.retrieve(QueryParser.java:150)
	at com.oracle.coherence.SqlTest.testQuery(SqlTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by npgall** [comment]
There's no way to do that I'm afraid. CQEngine doesn't support all features of SQL. It only supports enough SQL to translate WHERE clauses into CQEngine queries.

However you can use the Java 8 streams support to transform a ResultSet of Car objects, to a Stream<Car>, and from there to a Stream<Boolean> of the values of 'success'. Does that help?

**Comment by xuan** [comment]
Unfortunately we are on Java 7.  It would be a great addition to your project if your able to support this.  Thanks for your quick response.

**Comment by npgall** [comment]
If you are on Java 7, you can use Google Guava to do this.

The CQEngine `ResultSet<Car>` is an `Iterable<Car>`. So you can use Guava to transform an `Iterable<Car>` to an `Iterable<Boolean>`.
