### ISSUE TITLE
OffHeap SQLiteIndex getConnection throwing error

### ISSUE THREAD

**Issue by tylaar** [npgall/cqengine#172]
Hi Niall,

First of all, thanks for releasing such a good library, it really helps a lot!

Recently due to our collection is huge, and is causing GC problem, we've switched it to OffHeap, both for the IndexedCollection's element, and it's index. And we've seen this when we are trying to perform operation on the collection: 

> Caused by: java.lang.Error: Maximum lock count exceeded 
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.fullTryAcquireShared(ReentrantReadWriteLock.java:528) 
        at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquireShared(ReentrantReadWriteLock.java:488) 
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1282) 
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727) 
        at com.googlecode.cqengine.persistence.offheap.OffHeapPersistence.getConnection(OffHeapPersistence.java:142) 
        at com.googlecode.cqengine.index.sqlite.RequestScopeConnectionManager.getConnection(RequestScopeConnectionManager.java:61) 
        at com.googlecode.cqengine.index.sqlite.SQLiteIndex$3.iterator(SQLiteIndex.java:338) 
        at com.googlecode.cqengine.resultset.common.WrappedResultSet.iterator(WrappedResultSet.java:39) 
        at com.googlecode.cqengine.resultset.common.WrappedResultSet.iterator(WrappedResultSet.java:39) 
        at com.googlecode.cqengine.resultset.closeable.CloseableResultSet.iterator(CloseableResultSet.java:44) 
        at com.googlecode.cqengine.resultset.closeable.CloseableResultSet.iterator(CloseableResultSet.java:44) 
        at java.lang.Iterable.spliterator(Iterable.java:101) 

Am I missing some configuration or is this related to SQLIteIndex's bug ? 

Thanks a lot!

**Comment by npgall** [comment]
It sounds like ResultSets might be getting leaked i.e. getting opened but not closed. 

When using off-heap or disk persistence you need to close the RS after use. You can use a try-with-resources block as you can find here: https://github.com/npgall/cqengine/blob/master/README.md#querying-with-persistence

Could this be happening in your app? If you still have issues if you can supply a test case I could investigate further.

**Comment by tylaar** [comment]
Thanks a lot Niall! It should be my ResultSet handling code issue! Btw, what happens if I don't close the connection? Does that hit the SHARED_UNIT limitation in ReadWriteLock and stucked there forever? Thanks!

**Comment by npgall** [comment]
A shared lock which is managed in the off heap persistence layer will remain open until the RS is closed. So if your app keeps opening ResultSets but not closing them then eventually no new requests will be able to access the collection. 

This particular issue only affects the off-heap persistence as there is a different concurrency model in disk persistence. However usage is the same in both cases as the resources will be released when the RS is closed.

You can read more about it here: http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/offheap/OffHeapPersistence.html

**Comment by tylaar** [comment]
Thank you Niall for your detailed answer! I will close this.
