### ISSUE TITLE
Error while parsing SQL LIKE query

### ISSUE THREAD

**Issue by vj126** [npgall/cqengine#196]
**An exception is occurring while parsing SQL LIKE for query: `"SELECT * FROM data WHERE name LIKE 'S%a%' ".`**

Logs:
Exception in thread "main" com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:35: **no viable alternative at input 'name LIKE 'S%a%'**'
	at com.googlecode.cqengine.query.parser.common.QueryParser$1.syntaxError(QueryParser.java:54)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:558)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:147)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.simpleQuery(SQLGrammarParser.java:942)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.query(SQLGrammarParser.java:461)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.whereClause(SQLGrammarParser.java:344)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.start(SQLGrammarParser.java:244)
	at com.googlecode.cqengine.query.parser.sql.SQLParser.parse(SQLParser.java:62)
	at com.googlecode.cqengine.query.parser.common.QueryParser.retrieve(QueryParser.java:150)
	at goodset.files.filter.cqengine.StringToCQueryDemo.main(StringToCQueryDemo.java:81)

**Comment by npgall** [comment]
Hi,

The SQL parser only supports a limited subset of SQL. It does not support LIKE clauses which have multiple % wildcards as in 'S%a%'. It only supports startsWith, endsWith and contains - i.e. it maps those to the corresponding CQEngine queries. 

You can find the grammar here: [SQLGrammar.g4](https://github.com/npgall/cqengine/blob/master/code/src/main/antlr4/com/googlecode/cqengine/query/parser/sql/grammar/SQLGrammar.g4)

Anyway - as a workaround you could look into splitting that SQL statement into two parts with an AND statement in the middle: "(name LIKE 'S%') AND (name LIKE '%a%')".

**Comment by vj126** [comment]
Hi,

In [SQLGrammar.g4](https://github.com/npgall/cqengine/blob/master/code/src/main/antlr4/com/googlecode/cqengine/query/parser/sql/grammar/SQLGrammar.g4),  if LIKE clause is mapped to matchesRegex clause, it is possible to solve all wildcard expressions. But following changes are needed to be done in LIKE clause
`   expr = expr.replace(".", "\\.");` 
`   expr = expr.replace("?", ".");` 
`   expr = expr.replace("%", ".*");` 
For reference : [stackoverflow](https://stackoverflow.com/a/898461).

**Comment by npgall** [comment]
If we map SQL LIKE queries to regexes, then it will bypass indexes.
So this is not something that I would like to do, for performance reasons.

If you could adapt your pull request so that it continues to map queries to startsWith, endsWith and contains; but then maps more complicated (and currently unsupported) patterns to regexes, then I'd be happy to merge that.

Basically, we need to continue to avail of as many indexes as possible when executing queries.

**Comment by npgall** [comment]
I will close this issue because as I mentioned above, that pull request will bypass indexes which would harm performance. Feel free to reopen if you'd like to revise the PR or discuss further. Thanks!
