### ISSUE TITLE
SQLiteIdentityIndex.DeserializingAttribute.getValue is sometimes asked to deserialize PK bytes instead of object bytes

### ISSUE THREAD

**Issue by atomashpolskiy** [npgall/cqengine#200]
Hi @npgall 

I'm facing a strange behavior of Disk+SQLite persistence ~~when the indexed type contains 2D array as one of the fields (i.e. if I change the `String[][]` field to a `Map<String,String>`, the problem goes away)~~. The problem is that upon adding a `DiskIndex` onto an `IndexedCollection` the FK of the `SQLIndex` that backs `SQLiteIdentityIndex` receives PK bytes (PK is a string SimpleAttribute) to deserialize into an instance of the indexed type (which is a custom type) and, quite obviously, fails. ~~Prior to that it successfully deserializes a number of objects (i.e. receives correct bytes), which makes me think that it's a bug (?)~~

**UPDATE**: this happens regardless of the type of the fields for all indices that are built on non-identity attributes. I did not encounter this problem with `Map` because an OOM happened before any of the non-identity indices were added.

```java
public SQLiteIdentityIndex(final SimpleAttribute<O, A> primaryKeyAttribute) {
    this.sqLiteIndex = new SQLiteIndex<A, O, byte[]>(
                primaryKeyAttribute,
                new SerializingAttribute(primaryKeyAttribute.getObjectType(), byte[].class),
                new DeserializingAttribute(byte[].class, primaryKeyAttribute.getObjectType()),
                "") {
            ...
        };
...
}

class DeserializingAttribute extends SimpleAttribute<byte[], O> {

        public DeserializingAttribute(Class<byte[]> objectType, Class<O> attributeType) {
            super(objectType, attributeType);
        }

        @Override
        public O getValue(byte[] bytes, QueryOptions queryOptions) {
            return pojoSerializer.deserialize(bytes);
        }
    }
```

Stacktrace:
```
Exception in thread "pool-2-thread-1" java.lang.IllegalStateException: Unable to bulk add rows to the index table: TICKER. Rolled back: true
	at com.googlecode.cqengine.index.sqlite.support.DBQueries.bulkAdd(DBQueries.java:320)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex.doAddAll(SQLiteIndex.java:468)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex.init(SQLiteIndex.java:634)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addAttributeIndex(CollectionQueryEngine.java:198)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addIndex(CollectionQueryEngine.java:160)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.addIndex(ConcurrentIndexedCollection.java:173)
	...
Caused by: java.lang.IllegalStateException: Unable to retrieve the ResultSet item.
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex$3$1.computeNext(SQLiteIndex.java:356)
	at com.googlecode.concurrenttrees.common.LazyIterator.tryToComputeNext(LazyIterator.java:60)
	at com.googlecode.concurrenttrees.common.LazyIterator.hasNext(LazyIterator.java:55)
	at com.googlecode.cqengine.persistence.support.sqlite.SQLiteObjectStore$1CloseableIteratorImpl.hasNext(SQLiteObjectStore.java:83)
	at com.googlecode.cqengine.persistence.support.ObjectSet$ObjectStoreAsObjectSet$1.hasNext(ObjectSet.java:132)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex$4$1.computeNextOrNull(SQLiteIndex.java:523)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex$4$1.computeNext(SQLiteIndex.java:514)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex$4$1.computeNext(SQLiteIndex.java:505)
	at com.googlecode.concurrenttrees.common.LazyIterator.tryToComputeNext(LazyIterator.java:60)
	at com.googlecode.concurrenttrees.common.LazyIterator.hasNext(LazyIterator.java:55)
	at com.googlecode.cqengine.index.sqlite.support.DBQueries.bulkAdd(DBQueries.java:297)
	... 11 more
Caused by: java.lang.IllegalStateException: Failed to deserialize object, object type: class ru.finam.services.search.TermId. Configure @PersistenceConfig.polymorphic if the collection will contain a mix of object types. Use the KryoSerializer.validateObjectIsRoundTripSerializable() method to test your object is compatible with CQEngine.
	at com.googlecode.cqengine.persistence.support.serialization.KryoSerializer.deserialize(KryoSerializer.java:130)
	at com.googlecode.cqengine.index.sqlite.SQLiteIdentityIndex$DeserializingAttribute.getValue(SQLiteIdentityIndex.java:259)
	at com.googlecode.cqengine.index.sqlite.SQLiteIdentityIndex$DeserializingAttribute.getValue(SQLiteIdentityIndex.java:251)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex$3$1.computeNext(SQLiteIndex.java:352)
	... 21 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 47, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.esotericsoftware.kryo.util.MapReferenceResolver.getReadObject(MapReferenceResolver.java:60)
	at com.esotericsoftware.kryo.Kryo.readReferenceOrNull(Kryo.java:857)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:707)
	at com.googlecode.cqengine.persistence.support.serialization.KryoSerializer.deserialize(KryoSerializer.java:124)
	... 24 more
```

Your help would be greatly appreciated!

**Comment by npgall** [comment]
Ignoring exceptions is not a good situation.
I have not seen this particular issue before, so at the moment I can only assume it's caused by some unusual usage in your application.

If you can post a test case or self contained example which demonstrates the problem I'd be happy to investigate.

**Comment by muhdkhokhar** [comment]
I am having same issue what was fix?

**Comment by npgall** [comment]
Exact same issue?

**Comment by atomashpolskiy** [comment]
AFAIR, the root cause of the problem in my case was setting the PK value
into two different columns at the same time. I don't remember the details,
sorry :) But it was definitely a misuse of the library.

**Comment by muhdkhokhar** [comment]
> 
> 
> Exact same issue?

Actually not. It was that backward/forward compatible issue which I have fixed using compatible serializer.

How can I vaccume the sql datbase?

**Comment by npgall** [comment]
See [Persistence.compact()](http://htmlpreview.github.io/?http://raw.githubusercontent.com/npgall/cqengine/master/documentation/javadoc/apidocs/com/googlecode/cqengine/persistence/disk/DiskPersistence.html#compact())
