### ISSUE TITLE
Trouble using CQEngine with IBM Websphere

### ISSUE THREAD

**Issue by stingers-destiny** [npgall/cqengine#212]
Hi, 

I began developing a Caching solution using CQEngine a few months ago. All works great on my machine but now when I deploy on my IBM Websphere (which uses IBM Java Version) I am not able to load my classes because of typetools used behind the Scene by CQengine

Here is the line of code 

public static SimpleAttribute<MeldDB, String> KEY = attribute("key", MeldDB::getKey);

defined in MeldDB.java

and the Problem on Websphere log is as follows:

```
Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: com.MeldDB$$Lambda$36/000000009B220F70, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
	at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1083)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1069)
	at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:847)
	at com.MeldDB.<clinit>(MeldDB.java:21)

```
Is there an alternative to using attributes or an alternative to typetools or some other Workaround?

**Comment by npgall** [comment]
Yes, take a look at [LambdaAttributes.md](https://github.com/npgall/cqengine/blob/master/documentation/LambdaAttributes.md) for a workaround. You'll need to specify the generic types explicitly. Once you do that, it should work fine on Websphere.

**Comment by ErickPol** [comment]
Confirming the solution above for the Amazon Corretto JDK

> Yes, take a look at [LambdaAttributes.md](https://github.com/npgall/cqengine/blob/master/documentation/LambdaAttributes.md) for a workaround. You'll need to specify the generic types explicitly. Once you do that, it should work fine on Websphere.

The solution also works for the Amazon Corretto SDK, which presents the same problem
