### ISSUE TITLE
JDBC3Connection.commit has been executed for a very long time

### ISSUE THREAD

**Issue by Yrp** [npgall/cqengine#216]
I use DiskIndex，the sqlite file size is 22gb.
Through jstack, I found that it took a long time to execute org.sqlite.jdbc3.JDBC3Connection.commit. Below is information about jstack.
```
"pool-17-thread-1" #140 prio=5 os_prio=0 tid=0x00007f7d3539b000 nid=0x34eb runnable [0x00007f7c5477c000]
   java.lang.Thread.State: RUNNABLE
        at org.sqlite.core.NativeDB.step(Native Method)
        - locked <0x00000001c2c57a50> (a org.sqlite.core.NativeDB)
        at org.sqlite.core.DB.exec(DB.java:147)
        - locked <0x00000001c2c57a50> (a org.sqlite.core.NativeDB)
        at org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
        at com.googlecode.cqengine.index.sqlite.support.DBUtils.commit(DBUtils.java:54)
        at com.googlecode.cqengine.index.sqlite.RequestScopeConnectionManager.close(RequestScopeConnectionManager.java:83)
        at com.googlecode.cqengine.persistence.disk.DiskPersistence.closeRequestScopeResources(DiskPersistence.java:208)
        at com.googlecode.cqengine.ConcurrentIndexedCollection.closeRequestScopeResourcesIfNecessary(ConcurrentIndexedCollection.java:501)
        at com.googlecode.cqengine.ConcurrentIndexedCollection.add(ConcurrentIndexedCollection.java:355)
```

**Comment by Yrp** [comment]
Thank you for your help

**Comment by npgall** [comment]
CQEngine delegates to SQLite for disk persistence. It sounds like such a delay might be caused by checkpointing.

CQEngine uses SQLite in WAL mode, and there are a lot of parameters for WAL mode which can be tuned: https://www.sqlite.org/wal.html

If you want to tune any of those parameters, you can do so by passing properties to the DiskPersistence object. You can find some documentation about this in the DiskPersistence class.

Have you tried tuning any of those parameters?

Also could you try with a newer version of CQEngine? 
In CQEngine >=3.1.0 the performance of DiskPersistence should be improved.

**Comment by npgall** [comment]
I will resolve this, as most likely that behavior is due to checkpointing as I mentioned above. And if so, there are some tuning parameters available which can be used to tune that. Feel free to reopen if you can provide more details or need more help with this.
