### ISSUE TITLE
DiskPersistence breaks with JRebel class loading

### ISSUE THREAD

**Issue by djechelon** [npgall/cqengine#230]
I am trying to instantiate cqengine when running using JRebel agent

Code

```
SimpleAttribute<MyObject, String> attribute = attribute(MyObject::getAkNumber); //getAkNumber returns String
IndexedCollection<MyObject> cache = new ConcurrentIndexedCollection<>(DiskPersistence.onPrimaryKeyInFile(attribute, fileDump));
```

Debugger value of `attribute`

    Attribute{objectType=class com.zeroturnaround.jrebelbase.facade.aw, attributeType=class java.lang.Object, attributeName='com.acme.NplDebtrakCacheCqEngineImpl$$Lambda$74/567511730'}

Exception

	Caused by: java.lang.IllegalStateException: Type class java.lang.Object not supported.
		at com.googlecode.cqengine.index.sqlite.support.DBUtils.getDBTypeForClass(DBUtils.java:124) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.index.sqlite.support.DBQueries.createIndexTable(DBQueries.java:84) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.index.sqlite.SQLiteIndex.doAddAll(SQLiteIndex.java:445) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.index.sqlite.SQLiteIndex.init(SQLiteIndex.java:634) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.index.sqlite.SQLiteIdentityIndex.init(SQLiteIdentityIndex.java:128) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.engine.CollectionQueryEngine.addAttributeIndex(CollectionQueryEngine.java:198) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.engine.CollectionQueryEngine.addIndex(CollectionQueryEngine.java:160) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.engine.CollectionQueryEngine.init(CollectionQueryEngine.java:114) ~[cqengine-3.0.0.jar:?]
		at com.googlecode.cqengine.ConcurrentIndexedCollection.<init>(ConcurrentIndexedCollection.java:93) ~[cqengine-3.0.0.jar:?]
		at com.acme.NplDebtrakCacheCqEngineImpl.<init>(NplDebtrakCacheCqEngineImpl.java:65) ~[classes/:?]
		at sun.reflect.GeneratedConstructorAccessor152.newInstance(Unknown Source) ~[?:?]
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45005) ~[?:1.8.0_92]
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_92]
		at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.22.RELEASE.jar:4.3.22.RELEASE]
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.3.22.RELEASE.jar:4.3.22.RELEASE]
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1152) ~[spring-beans-4.3.22.RELEASE.jar:4.3.22.RELEASE]
		... 67 more

Workaround is to start my application without JRebel agent, which prevents me to hot swap classes

**Comment by djechelon** [comment]
Okay, I found myself a potential fix. By explicitly invoking the attribute builder with source and destination classes I can overcome the problem with lambda expressions.

    cache.addIndex(DiskIndex.onAttribute(attribute(MyClass.class, String.class, "myAttribute", MyClass::getMyAttribute)));

Not closing the issue for posterity

**Comment by npgall** [comment]
I would frame this as JRebel causing the issue rather than CQEngine.

It is wrapping the objects in some kind of facade, such that the DiskPersistence cannot identify the type of object it needs to persist.

This issue relates to use of CQEngine attributes generated from lambdas/method references, and you can find background info on the problem and the workaround you ended up using, in [LambdaAttributes.md](https://github.com/npgall/cqengine/blob/master/documentation/LambdaAttributes.mdhttps://github.com/npgall/cqengine/blob/master/documentation/LambdaAttributes.md).

I will close this as I don't think there is anything that can be done on the CQEngine side.
