### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Thiruvengadam** [npgall/cqengine#252]
Hi, 
In my proj we are using old spring version which is 3.0.5 and when I add cqengine dependency I am getting below error. I googled and found out that its due to asm incompatibility. Although i excluded spring asm from the maven its not working. Any pointers to this error would help.
I am using CQengine 2.11.0

java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected

	at com.esotericsoftware.reflectasm.ConstructorAccess.insertConstructor(ConstructorAccess.java:128)
	at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:98)
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1271)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1127)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1136)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:562)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:538)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:709)
	at com.googlecode.cqengine.index.sqlite.support.PojoSerializer.deserialize(PojoSerializer.java:84)
	at com.googlecode.cqengine.index.sqlite.SQLiteIdentityIndex$DeserializingAttribute.getValue(SQLiteIdentityIndex.java:243)
	at com.googlecode.cqengine.index.sqlite.SQLiteIdentityIndex$DeserializingAttribute.getValue(SQLiteIdentityIndex.java:235)
	at com.googlecode.cqengine.index.sqlite.SQLiteIndex$3$1.computeNext(SQLiteIndex.java:352)
	at com.googlecode.concurrenttrees.common.LazyIterator.tryToComputeNext(LazyIterator.java:60)
	at com.googlecode.concurrenttrees.common.LazyIterator.hasNext(LazyIterator.java:55)
	at com.googlecode.cqengine.persistence.support.sqlite.SQLiteObjectStore$1CloseableIteratorImpl.hasNext(SQLiteObjectStore.java:83)
	at com.googlecode.cqengine.ConcurrentIndexedCollection$3.hasNext(ConcurrentIndexedCollection.java:300)

**Comment by Thiruvengadam** [comment]
I am closing this as I found the solution. Its to use kryo-shaded which will have inbuilt asm files.
