### ISSUE TITLE
Java 14 -> IllegalStateException: Could not resolve sufficient generic type information

### ISSUE THREAD

**Issue by Verdoso** [npgall/cqengine#269]
Hi,
I have an application that runs fine with Java 8 and 11 but if I run it with Java 14, I get this error:
```
Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: org.greeneyed.epl.librarian.model.Libro$$Lambda$569/0x0000000801026440, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
        at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1136)
        at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1122)
        at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:900)
        at org.greeneyed.epl.librarian.model.Libro.<clinit>(Libro.java:42)
```
The code where it breaks is a simple attribute definition:
```
public static final SimpleAttribute<Libro, Integer> LIBRO_ID = attribute(LIBRO_ID_PARAM,Libro::getId);
```
Where getId() returns an Integer.

The solution is to change the attribute defition so it includes the type attributes explicitely
```
public static final SimpleAttribute<Libro, Integer> LIBRO_ID = attribute(Libro.class, Integer.class, LIBRO_ID_PARAM,Libro::getId);
```
and that way, it works with all JDKs.

It might be a JDK or TypeResolver limitation, and it is documented, but I wanted to open an issue so people looking for a solution would be able to find it easily.

Cheers!

**Comment by npgall** [comment]
Thanks for reporting this actually. This is definitely something that I think CQEngine should support if possible on Java 14.

Right now, there is actually no official support to read generic types from lambda expressions. Each specific JVM requires a different method to achieve that. 

Currently CQEngine uses a helpful library called TypeTools to do this. It implements those different strategies depending on the host JVM.

My guess is that in Java 14, the internal APIs were changed such that Type Tools can't do that. When this happens CQEngine will then throw that exception  you saw.

This might be the root cause: https://github.com/jhalterman/typetools/issues/56

Unfortunately I don't see a newer version of TypeTools yet, which might support newer JVMs. So I am not sure what we can do about it currently. I'll keep this issue open until we can find a solution.

**Comment by sheinbergon** [comment]
@npgall  @Verdoso  a new version of typetools has been released 20 days ago, and judging by the changelog, it resolves this issue.

**Comment by lvitaly** [comment]
Same for JDK 17

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.company.jl.service.cache.Cache.<init>(Cache.java:27)
        at com.company.jl.App.main(App.java:38)
Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: com.company.jl.service.cache.Members$$Lambda$137/0x0000000800e1bd28, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
        at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1136)
        at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1122)
        at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:900)
        at com.company.jl.service.cache.Members.<clinit>(Members.java:30)
        ... 2 more
```

**Comment by lvitaly** [comment]
@sheinbergon, I have tried to update typetools to v0.6.3, antlr4 to v4.9.2, and kryo to v5.2.0, but I got exceptions with [kryo-serializers](https://github.com/magro/kryo-serializers) in tests. Particularly in the next rows
```
        kryo.register(Arrays.asList().getClass(), new ArraysAsListSerializer());
        UnmodifiableCollectionsSerializer.registerSerializers(kryo);
        SynchronizedCollectionsSerializer.registerSerializers(kryo);
```

**Comment by lvitaly** [comment]
@npgall, maybe you have some ideas?

**Comment by lvitaly** [comment]
`Arrays.asList().getClass()` already added in kryo v5.0.0 default serialisers (see [Kryo.java#L225](https://github.com/EsotericSoftware/kryo/blob/a2dfa5c8c2ea6f6fbb264199ef7e2ab972424190/src/com/esotericsoftware/kryo/Kryo.java#L225)), so it can be dropped.

**Comment by lvitaly** [comment]
I bumped dependencies and disabled serializers above (see https://github.com/lvitaly/cqengine/commit/393fc030c799f04e81b9e1f77bf6e0e25fdf2af3). Only one test failed, and two skipped in the result.
```
```
Results :

Failed tests:   testEqualsAndHashCode(com.googlecode.cqengine.attribute.ReflectiveAttributeTest): EqualsVerifier found a problem in class com.googlecode.cqengine.attribute.ReflectiveAttribute.(..)

Tests run: 10825, Failures: 1, Errors: 0, Skipped: 2
```
