### ISSUE TITLE
SQLParser fails when mixed logic expression not explicitly parenthesized

### ISSUE THREAD

**Issue by clayembry** [npgall/cqengine#279]
SLQParser fails to parse valid SQL expressions with mixed logical operators (AND / OR) unless they are explicitly parenthesized. For example, this valid SQL expression throws a parsing exception.
```
sqlParser.parse("select * from MyObj where (attr1 = 'true' AND attr2 = 'true' OR attr3 = 'true')");
```
The exception is:
```
com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:61: mismatched input 'OR' expecting {')', K_AND}

	at com.googlecode.cqengine.query.parser.common.QueryParser$1.syntaxError(QueryParser.java:54)
```

According to SQL documentation, that expression should be valid and should be evaluated according to operator order of precedence (AND evaluated first, then OR). https://dev.mysql.com/doc/refman/8.0/en/operator-precedence.html

If I explicitly parenthesize the expression, it parses fine:
```
sqlParser.parse("select * from MyObj where ((attr1 = 'true' AND attr2 = 'true') OR attr3 = 'true')");
```

**Comment by huangsanyeah** [comment]
i

> SLQParser fails to parse valid SQL expressions with mixed logical operators (AND / OR) unless they are explicitly parenthesized. For example, this valid SQL expression throws a parsing exception.
> 
> ```
> sqlParser.parse("select * from MyObj where (attr1 = 'true' AND attr2 = 'true' OR attr3 = 'true')");
> ```
> 
> The exception is:
> 
> ```
> com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:61: mismatched input 'OR' expecting {')', K_AND}
> 
> 	at com.googlecode.cqengine.query.parser.common.QueryParser$1.syntaxError(QueryParser.java:54)
> ```
> 
> According to SQL documentation, that expression should be valid and should be evaluated according to operator order of precedence (AND evaluated first, then OR). https://dev.mysql.com/doc/refman/8.0/en/operator-precedence.html
> 
> If I explicitly parenthesize the expression, it parses fine:
> 
> ```
> sqlParser.parse("select * from MyObj where ((attr1 = 'true' AND attr2 = 'true') OR attr3 = 'true')");
> ```

i also met this problem,
it seems we must use "()" to deal this
waiting for reply
tks
