### ISSUE TITLE
Thread blocked when using Materialized View Sort For the Longest Prefix for CSV that contain more than 11 K rows

### ISSUE THREAD

**Issue by fouadazem** [npgall/cqengine#310]
Hi @npgall ,

when using the below query 

2022-11-17 02:22:30,310 [vert.x-eventloop-thread-10] DEBUG c.o.s.r.q.g.impl.QueryGeneratorImpl -  - Generated query parameter instance with config options: query       : and(lessThanOrEqualTo("Valid_From", 1648647740), greaterThanOrEqualTo("Valid_To", 1648647740), matchesRegexOf("Carrier_PATTERN", GenericCarrier), matchesRegexOf("CallType_PATTERN", VOICE), equal("ANumberPrefix", "*"), longestPrefix("BNumberPrefix", "1901101101"))
when having big number of rows in the CSV .

we are getting the below exception :-

ov 17, 2022 2:22:30 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-10,5,main]=Thread[vert.x-eventloop-thread-10,5,main] has been blocked for 5617 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.util.concurrent.ConcurrentHashMap$Traverser.advance(ConcurrentHashMap.java:3339)
	at java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3419)
	at com.googlecode.cqengine.persistence.support.CollectionWrappingObjectStore$1.next(CollectionWrappingObjectStore.java:67)
	at com.googlecode.cqengine.persistence.support.ObjectSet$ObjectStoreAsObjectSet$1.next(ObjectSet.java:137)
	at com.googlecode.cqengine.query.comparative.LongestPrefix.getMatchesForSimpleAttribute(LongestPrefix.java:63)
	at com.googlecode.cqengine.query.comparative.SimpleComparativeQuery.getMatches(SimpleComparativeQuery.java:92)
	at com.googlecode.cqengine.index.fallback.FallbackIndex$1.iterator(FallbackIndex.java:109)
	at com.googlecode.cqengine.resultset.iterator.IteratorUtil.iterableContains(IteratorUtil.java:31)
	at com.googlecode.cqengine.index.fallback.FallbackIndex$1.contains(FallbackIndex.java:123)
	at com.googlecode.cqengine.resultset.common.WrappedResultSet.contains(WrappedResultSet.java:44)
	at com.googlecode.cqengine.resultset.connective.ResultSetIntersection.contains(ResultSetIntersection.java:101)
	at com.googlecode.cqengine.resultset.common.WrappedResultSet.contains(WrappedResultSet.java:44)
	at com.googlecode.cqengine.resultset.connective.ResultSetIntersection$1.isValid(ResultSetIntersection.java:66)
	at com.googlecode.cqengine.resultset.filter.FilteringIterator.hasNext(FilteringIterator.java:52)
	at com.googlecode.cqengine.resultset.iterator.IteratorUtil.materializedSort(IteratorUtil.java:199)
	at com.googlecode.cqengine.resultset.order.MaterializedOrderedResultSet.iterator(MaterializedOrderedResultSet.java:74)
	at com.googlecode.cqengine.resultset.closeable.CloseableResultSet.iterator(CloseableResultSet.java:44)
	at com.googlecode.cqengine.resultset.closeable.CloseableResultSet.iterator(CloseableResultSet.java:44)
	at com.googlecode.cqengine.resultset.ResultSet.spliterator(ResultSet.java:208)
	at com.googlecode.cqengine.resultset.ResultSet.stream(ResultSet.java:220)
	at com.openet.sba.refdata.impl.sets.ReferenceDataSetImpl.getResultStream(ReferenceDataSetImpl.java:102)
	at com.openet.sba.refdata.impl.sets.ReferenceDataSetImpl.retrieveAsStream(ReferenceDataSetImpl.java:74)

as we see the Thread blocked inside cqengine and we are using version 3.5.0 version  of the CQEngine code.

is there any limitation for the Materialized when using longest for such data of 11 k rows inside the file ?

do you face such scenarios on the previous and maybe its handled in the later version of CQEngine ?

Any direction to fix that in any direction you can point for us ?

B.R,
Fouad Azem

**Comment by npgall** [comment]
Hmm, I am not sure.

Which kind of persistence are you using? On-heap/off-heap/disk?

The only blocking that can occur indefinitely as far as I know, is when using off-heap or disk persistence, when the application fails to call `ResultSet.close()` when it has finished with the results. Could that be a culprit? If you are using on-heap persistence that should not be a culprit.

**Comment by fouadazem** [comment]
Hi @npgall ,

I see , m working with application on Heap which is base The event loop must never be blocked, if it is then you will exactly that message from above from thrown because the query into the Cqengine took more time than its expected , so our event look report on that as Thread blocked since the response comes back in acceptable time frame.
I tried to work with Data inside the CSV which is around 11K  and the response were taking i check it individually around 12 sec with the current implementation.
is there any recommendation base on cqengine documentation with how much data we should work on the CSV ?
is 11K is valid scenario ,if there was benchmarking with such scenario ?
every API has limit if data , does the CQ Engine have such ? 
what is the acceptable time that we should get response from the CQEngine when working with Longest Prefix match with the current implementation ?

Regards Fouad Azem

**Comment by npgall** [comment]
I see.

I had assumed when you (and that BlockedThreadChecker utility) said the thread is blocked, that you (or it) meant the thread was blocked waiting to acquire some kind of mutex or lock (i.e. indicating there was some kind of deadlock at play). 

But based on your last post, it sounds like by "blocked" it means the thread is just busy? So it means your query just has high latency, as opposed to there being some kind of deadlock occurring. Is that the case?

CSV manipulation is not part of CQEngine, so I guess your implementation of attributes might be parsing the CSV? 

Generally CQEngine might invoke attributes many times to process a query. It expects the implementation of an attribute to be fast. So if you are doing expensive computations inside attributes (like parsing CSV on-the-fly) that can cause latency.

To reduce latency, consider parsing your CSV into Java objects before you load them into CQEngine, such that your attributes can then just read fields in the objects which will be fast.

If that is not possible, follow the general guidance in the documentation about adding indexes to accelerate your queries. 

You could also look at using the "index" [merge strategy](https://github.com/npgall/cqengine/blob/master/documentation/MergeStrategies.md) instead of the default merge strategy.

The "index" merge strategy aims to avoid invoking attributes as much as possible (it assumes invoking them is expensive), and instead it will try to evaluate the query by doing JOINs between indexes under the hood.

Hope that helps. I will close this because I think this is not an issue with CQEngine itself, but rather with CSV parsing. Feel free to reopen if you need more help on the CQEngine side though.
