### ISSUE TITLE
Error while parsing SQL NOT LIKE query

### ISSUE THREAD

**Issue by sxpujs** [npgall/cqengine#312]
sql:
```select * from collection where (f7_text not like '%3%')```

java code:
```
@Test
public void test1() {
    System.out.println("sssss");
    IndexedCollection<Map> entityList = new ConcurrentIndexedCollection<>();

    Map map1 = new HashMap();
    map1.put("f7_text", "1111");

    Map map2 = new HashMap();
    map2.put("f7_text", "3333");
    entityList.add(map1);
    entityList.add(map2);
    ResultSet<Map>
            results = sqlParser.retrieve(entityList, "select * from collection where (f7_text not like '%3%')");
    results.forEach(System.out::println); // Prints: Honda Accord, Ford Fusion, Ford Focus
}
```

error message:
```
com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:44: no viable alternative at input '(f7_text not like'

	at com.googlecode.cqengine.query.parser.common.QueryParser$1.syntaxError(QueryParser.java:54)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.query(SQLGrammarParser.java:474)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.whereClause(SQLGrammarParser.java:349)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.start(SQLGrammarParser.java:245)
	at com.googlecode.cqengine.query.parser.sql.SQLParser.parse(SQLParser.java:62)
	at com.googlecode.cqengine.query.parser.common.QueryParser.retrieve(QueryParser.java:150)
```

**Comment by sxpujs** [comment]
I refered https://github.com/npgall/cqengine/issues/119, and put not before the viable.
