### ISSUE TITLE
Does CQEngine compatible with Java 17

### ISSUE THREAD

**Issue by Nikhilkarande33** [npgall/cqengine#320]
Hi Team,

we are planning to move our application to java 17, during migration we encountered with below error

`Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: $$Lambda$930/0x0000000801aa5790, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
	at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1136)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1122)
	at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:900)
	at com.xAndAlertCache.java:82)`
	
Does CQEngine compatible with Java 17? Please suggest.

**Comment by ilgvarsj** [comment]
I had similar issue, 'fixed' by explicitly specifying attribute name:

`    public static final Attribute<TxItem, String> LOCAL_ACCOUNT = nullableAttribute(TxItem.class, String.class, "localAccount", TxItem::getLocalAccount);`

**Comment by simplecoin-eu** [comment]
possible duplicate: https://github.com/npgall/cqengine/issues/304
