### ISSUE TITLE
CQN dates

### ISSUE THREAD

**Issue by djechelon** [npgall/cqengine#53]
Hi,

how do I query with CQN a field that is type Date?

I am building a dynamic expression engine. So far I have translated `between` expression with two date as follows

      between("logDate","1456441200000","1456613999999"); //using Date.getTime()

However CQ Engine is unhappy

```
Caused by: java.lang.NoSuchMethodException: java.util.Date.valueOf(java.lang.String)
at java.lang.Class.getMethod(Class.java:1670) ~[?:1.7.0_79]
	at com.googlecode.cqengine.query.parser.cqn.support.FallbackValueParser.parse(FallbackValueParser.java:39) ~[cqengine-2.1.0.jar:?]
	at com.googlecode.cqengine.query.parser.common.QueryParser.parseValue(QueryParser.java:128) ~[cqengine-2.1.0.jar:?]
	at com.googlecode.cqengine.query.parser.common.QueryParser.parseValue(QueryParser.java:113) ~[cqengine-2.1.0.jar:?]
	at com.googlecode.cqengine.query.parser.cqn.support.CQNAntlrListener.exitBetweenQuery(CQNAntlrListener.java:127) ~[cqengine-2.1.0.jar:?]
	at com.googlecode.cqengine.query.parser.cqn.grammar.CQNGrammarParser$BetweenQueryContext.exitRule(CQNGrammarParser.java:1144) ~[cqengine-2.1.0.jar:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[antlr4-runtime-4.5.2-1.jar:4.5.2-1]
	at com.googlecode.cqengine.query.parser.cqn.CQNParser.parse(CQNParser.java:69) ~[cqengine-2.1.0.jar:?]
	at com.googlecode.cqengine.query.parser.common.QueryParser.retrieve(QueryParser.java:150) ~[cqengine-2.1.0.jar:?]
```

What is the correct way to implement `Date` fields querying in CQN? I can successfully use attribute querying for `Date`s.

Thanks

**Comment by djechelon** [comment]
Ok for now I have implemented a workaround

    parser.registerValueParser(Date.class, new ValueParser<Date>()
            {

                @Override
                protected Date parse(Class<? extends Date> paramClass, String paramString)
                {
                    if (isEmpty(paramString))
                        return null;
                    if (paramString.startsWith("\""))
                        paramString = paramString.substring(1);
                    if (paramString.endsWith("\""))
                        paramString = paramString.substring(0, paramString.length() - 1);
                    return new Date(Long.valueOf(paramString));
                }
            });


But I am pretty sure that I have encoded the date the wrong way :smile:

**Comment by npgall** [comment]
Hi djechelon,

Actually that is the correct way to do it.

You could take a look at this post in the discussion group for some other examples: https://groups.google.com/d/msg/cqengine-discuss/Pvs0reAYC9U/G1u0Dm43BQAJ

HTH,
Niall
