### ISSUE TITLE
mismatched input 'AND' expecting <EOF>

### ISSUE THREAD

**Issue by lxzylllsl** [npgall/cqengine#65]
When I build SQL like select * from eus where private_category='power' AND regionId='330104'
comes the exception like this:
`
com.googlecode.cqengine.query.parser.common.InvalidQueryException: Failed to parse query at line 1:48: mismatched input 'AND' expecting <EOF>
	at com.googlecode.cqengine.query.parser.common.QueryParser$1.syntaxError(QueryParser.java:54)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:558)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:150)
	at com.googlecode.cqengine.query.parser.sql.grammar.SQLGrammarParser.start(SQLGrammarParser.java:263)
	at com.googlecode.cqengine.query.parser.sql.SQLParser.parse(SQLParser.java:62)
	at com.googlecode.cqengine.query.parser.common.QueryParser.retrieve(QueryParser.java:150)
`

is there any Error in the SQL?

**Comment by npgall** [comment]
At the moment the SQL parser is a bit strict and it needs you to put
brackets around the AND expression.

**Comment by lxzylllsl** [comment]
Thanks a lot! Problem solved. :)
