### ISSUE TITLE
ClassCastException when using compound index

### ISSUE THREAD

**Issue by devinrsmith** [npgall/cqengine#85]
Source here: https://gist.github.com/devinrsmith/946e658369f3b4f9432d5385ee0adf1e

Throws:

```
Exception in thread "main" java.lang.ClassCastException: com.googlecode.cqengine.query.simple.In cannot be cast to com.googlecode.cqengine.query.simple.Equal
	at com.googlecode.cqengine.index.compound.support.CompoundQuery.getCompoundValueTuple(CompoundQuery.java:76)
	at com.googlecode.cqengine.index.compound.CompoundIndex.retrieve(CompoundIndex.java:122)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.retrieveRecursive(CollectionQueryEngine.java:907)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.retrieveWithoutIndexOrdering(CollectionQueryEngine.java:482)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.retrieve(CollectionQueryEngine.java:460)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.retrieve(ConcurrentIndexedCollection.java:110)
```

**Comment by npgall** [comment]
Hi Devin,

Thanks for the bug report. I've fixed this in mainline! It was never intended that the engine would try to use a CompoundIndex with any types of query except Equal. So I've updated it to validate that queries actually are instances of Equal now.

Thanks!
Niall
