### ISSUE TITLE
Null Double values in index, and wrapping in getOrDefault

### ISSUE THREAD

**Issue by jacobg** [npgall/cqengine#93]
I created a Navigable Index using DoubleQuantizer, and see NPE when a null value is added:

```
java.lang.NullPointerException
	at com.googlecode.cqengine.quantizer.DoubleQuantizer$TruncatingQuantizer.getQuantizedValue(DoubleQuantizer.java:53)
	at com.googlecode.cqengine.quantizer.DoubleQuantizer$TruncatingQuantizer.getQuantizedValue(DoubleQuantizer.java:49)
	at com.googlecode.cqengine.index.navigable.NavigableIndex$8.getQuantizedValue(NavigableIndex.java:559)
	at com.googlecode.cqengine.index.navigable.NavigableIndex$8.getQuantizedValue(NavigableIndex.java:509)
	at com.googlecode.cqengine.index.support.AbstractMapBasedAttributeIndex.addAll(AbstractMapBasedAttributeIndex.java:78)
	at com.googlecode.cqengine.engine.CollectionQueryEngine$12.perform(CollectionQueryEngine.java:1125)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.forEachIndexDo(CollectionQueryEngine.java:1206)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addAll(CollectionQueryEngine.java:1122)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.add(ConcurrentIndexedCollection.java:351)
```

For null values, it's fine to use a 0 default. So I tried to wrap my attribute function using a getOrDefault like this:

```
	private static <O> SimpleFunction<O, Double> getOrDefault(SimpleFunction<O, Double> function,
	                                                          Double defaultValue)
	{
		return object -> {
			Double value = function.apply(object);
			return value != null ? value : defaultValue;
		};
	}
```

And then I'd define an attribute like this:
```
	private static final Attribute<Node, Double> SCORE =
			attribute(getOrDefault(Node::getScore, 0.0));
```

The problem with that workaround is I have multiple attributes which use this getOrDefault wrapper. And that causes CQEngine to throw an exception that it thinks I am adding a duplicate index. That's because those multiple attributes all have the same class name due to the wrapper.

```
java.lang.IllegalStateException: An equivalent index has already been added for attribute: Attribute{objectType=class java.lang.Object, attributeType=class java.lang.Double, attributeName='com.<REMOVED>$$Lambda$23/795590320'}
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addAttributeIndex(CollectionQueryEngine.java:188)
	at com.googlecode.cqengine.engine.CollectionQueryEngine.addIndex(CollectionQueryEngine.java:158)
	at com.googlecode.cqengine.ConcurrentIndexedCollection.addIndex(ConcurrentIndexedCollection.java:173)
```

Do you have any thoughts about this case?

Thanks!

**Comment by npgall** [comment]
I'm away from my computer so I'm not sure I understand the problem.  But if
your data will contain null values, you'll need to use nullableAttribute(),
instead of attribute(). Does that help?

Sent from my Android

On 11 Oct 2016 16:24, "jacobg" <notifications@github.com> wrote:

I created a Navigable Index using DoubleQuantizer, and see NPE when a null
value is added:

java.lang.NullPointerException
    at com.googlecode.cqengine.quantizer.DoubleQuantizer$TruncatingQuantizer.getQuantizedValue(DoubleQuantizer.java:53)
    at com.googlecode.cqengine.quantizer.DoubleQuantizer$TruncatingQuantizer.getQuantizedValue(DoubleQuantizer.java:49)
    at com.googlecode.cqengine.index.navigable.NavigableIndex$8.getQuantizedValue(NavigableIndex.java:559)
    at com.googlecode.cqengine.index.navigable.NavigableIndex$8.getQuantizedValue(NavigableIndex.java:509)
    at com.googlecode.cqengine.index.support.AbstractMapBasedAttributeIndex.addAll(AbstractMapBasedAttributeIndex.java:78)
    at com.googlecode.cqengine.engine.CollectionQueryEngine$12.perform(CollectionQueryEngine.java:1125)
    at com.googlecode.cqengine.engine.CollectionQueryEngine.forEachIndexDo(CollectionQueryEngine.java:1206)
    at com.googlecode.cqengine.engine.CollectionQueryEngine.addAll(CollectionQueryEngine.java:1122)
    at com.googlecode.cqengine.ConcurrentIndexedCollection.add(ConcurrentIndexedCollection.java:351)

For null values, it's fine to use a 0 default. So I tried to wrap my
attribute function using a getOrDefault like this:

    private static <O> SimpleFunction<O, Double>
getOrDefault(SimpleFunction<O, Double> function,
                                                              Double
defaultValue)
    {
        return object -> {
            Double value = function.apply(object);
            return value != null ? value : defaultValue;
        };
    }

And then I'd define an attribute like this:

    private static final Attribute<Node, Double> SCORE =
            attribute(getOrDefault(Node::getScore, 0.0));

The problem with that workaround is I have multiple attributes which use
this getOrDefault wrapper. And that causes CQEngine to throw an exception
that it thinks I am adding a duplicate index. That's because those multiple
attributes all have the same class name due to the wrapper.

java.lang.IllegalStateException: An equivalent index has already been
added for attribute: Attribute{objectType=class java.lang.Object,
attributeType=class java.lang.Double,
attributeName='com.<REMOVED>$$Lambda$23/795590320'}
    at com.googlecode.cqengine.engine.CollectionQueryEngine.addAttributeIndex(CollectionQueryEngine.java:188)
    at com.googlecode.cqengine.engine.CollectionQueryEngine.addIndex(CollectionQueryEngine.java:158)
    at com.googlecode.cqengine.ConcurrentIndexedCollection.addIndex(ConcurrentIndexedCollection.java:173)

Do you have any thoughts about this case?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/npgall/cqengine/issues/93>, or mute the thread

**Comment by jacobg** [comment]
It does prevent the NPE. But it doesn't provide a default value, and so nothing gets indexed. I have to think through whether I want it to be indexed at all, and at what value (e.g., 0) If I do want a default value, I guess I can just do the longhand notation of:

	private static final SimpleAttribute<Node, Double> SCORE      =
			new SimpleAttribute<Node, Double>("score") {
				public String getValue(Node node, QueryOptions queryOptions) {
					return node.getScore() != null ? node.getScore() : 0.0;
				}
			};

I think this issue can be closed.

Thanks again!

**Comment by npgall** [comment]
No problem.

Btw if you want to index objects with null values, take a look at
QueryFactory.forObjectsMissing(). This will allow you to quickly retrieve
objects where a has() query would return false.

You can also use this with index-accelerated ordering (you can read about
OrderingStrategies in the documentation folder)

HTH!
Niall

**Comment by jacobg** [comment]
Very helpful! Thank you!
